name: CI Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - "helm/**"
      - "kubernetes/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4

      - name: Build
        run: go build -o main .
  golangci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golang-lint

        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
  docker:
    name: Docker

    needs: [build, golangci]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ vars.DOCKER_USER }}/web-go-app:${{ github.sha }}
          context: .

      - name: Test Docker Image
        run: |
          docker images
          docker run --name web-go-app -d \
                -p 8080:8080 \
                ${{ vars.DOCKER_USER }}/web-go-app:${{ github.sha }}
          echo "Waiting for the container to start..."
          docker container ls

      - name: Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKER_USER }}/web-go-app:${{ github.sha }}
          context: .
  update-changes:
    needs: docker
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: edit values in helm chart
        run: |

          sed -i "s|name: .*|name: \"${{ vars.DOCKER_USER }}/web-go-app\"|" helm/web-go-app/values.yaml
          sed -i "s|tag: .*|tag: \"${{ github.sha}}\"|" helm/web-go-app/values.yaml

      - name: commit changes and push to github
        run: |
          git config --global user.email "ahmedmoghazy@gmail.com"
          git config --global user.name "amoghazy"
          git add helm/web-go-app/values.yaml 
          git commit -m "update values in helm chart-${{ github.sha}}"
          git push
